import { pick } from "./locale";

/**
 * Company identity, contact details and navigation.
 * Recovered from the legacy Angular footer — these are the real, verified
 * details. The React build previously showed "Lagos, Nigeria", which was wrong.
 */

export const COMPANY = {
  name: "eMalyami",
  shortName: "eMa",
  legalEntity: "SobekIMF (Pty) Ltd",
  patentNumber: "2020/06393",
  address: {
    en: "Sobek House, 452 Ontdekkers Rd., Florida Park, Roodepoort, Gauteng, South Africa, 1709",
    ar: "بيت سوبك، 452 طريق أونتدِكرز، فلوريدا بارك، رودِبورت، خاوتينخ، جنوب أفريقيا، 1709",
    fr: "Sobek House, 452 Ontdekkers Rd., Florida Park, Roodepoort, Gauteng, Afrique du Sud, 1709",
    pt: "Sobek House, 452 Ontdekkers Rd., Florida Park, Roodepoort, Gauteng, África do Sul, 1709",
  },
  phone: "+27 (0) 11 472 9294",
  email: {
    general: "info@emalyami.com",
    compliance: "compliance@emalyami.com",
    support: "support@emalyami.com",
  },
  social: {
    facebook: "https://www.facebook.com/emalyamiapp",
    instagram: "https://www.instagram.com/emalyamiapp",
    linkedin: "https://www.linkedin.com/company/emalyami/",
    twitter: "https://twitter.com/EMalyami",
  },
  apps: {
    main: "https://play.google.com/store/apps/details?id=com.emalyami.mobile",
  },
  website: "https://ema.emalyami.com/",
  blog: "https://emalyami.wordpress.com/",
};

export const NAV = pick({
  en: [
    { id: "modules", label: "Modules", type: "route", to: "/modules" },
    { id: "industries", label: "Industries", type: "scroll" },
    { id: "pricing", label: "Pricing", type: "scroll" },
    { id: "white-label", label: "White label", type: "scroll" },
    { id: "partner", label: "Partner", type: "scroll" },
    { id: "/faq", label: "FAQ", type: "route", to: "/faq" },
    { id: "/news", label: "News", type: "route", to: "/news" },
  ],
  ar: [
    { id: "modules", label: "الوحدات", type: "route", to: "/modules" },
    { id: "industries", label: "القطاعات", type: "scroll" },
    { id: "pricing", label: "الأسعار", type: "scroll" },
    { id: "white-label", label: "العلامة البيضاء", type: "scroll" },
    { id: "partner", label: "الشراكة", type: "scroll" },
    { id: "/faq", label: "الأسئلة الشائعة", type: "route", to: "/faq" },
    { id: "/news", label: "الأخبار", type: "route", to: "/news" },
  ],
  fr: [
    { id: "modules", label: "Modules", type: "route", to: "/modules" },
    { id: "industries", label: "Secteurs", type: "scroll" },
    { id: "pricing", label: "Tarifs", type: "scroll" },
    { id: "white-label", label: "Marque blanche", type: "scroll" },
    { id: "partner", label: "Partenariat", type: "scroll" },
    { id: "/faq", label: "FAQ", type: "route", to: "/faq" },
    { id: "/news", label: "Actualités", type: "route", to: "/news" },
  ],
  pt: [
    { id: "modules", label: "Módulos", type: "route", to: "/modules" },
    { id: "industries", label: "Setores", type: "scroll" },
    { id: "pricing", label: "Preços", type: "scroll" },
    { id: "white-label", label: "Marca branca", type: "scroll" },
    { id: "partner", label: "Parcerias", type: "scroll" },
    { id: "/faq", label: "FAQ", type: "route", to: "/faq" },
    { id: "/news", label: "Notícias", type: "route", to: "/news" },
  ],
});

export const UI = pick({
  en: {
    getStarted: "Start free",
    getStartedShort: "Start free",
    learnMore: "Learn more",
    seeAllModules: "See all 14 modules",
    downloadApp: "Get it on Google Play",
    openWebApp: "Open the web app",
    contactUs: "Contact us",
    menu: "Navigation",
    close: "Close menu",
    language: "Language",
    backToModules: "All modules",
    worksWellWith: "Works well with",
    whatItIs: "What it is",
    howItWorks: "How it works",
    everythingItDoes: "Everything it does",
    whoItsFor: "Who it's for",
    whatItCosts: "What it costs",
    whereItSettles: "Where it settles",
    seeItWork: "See it work",
    moneyStack: "Money Stack",
    businessStack: "Business Stack",
    status: { live: "Live", beta: "Beta", planned: "Planned" },
    filterAll: "All",
    browse: "Browse",
    company: "Company",
    support: "Support",
    legal: "Legal",
    followUs: "Follow us",
    rightsReserved: "All rights reserved.",
    poweredBy: "Powered by",
    patentNo: "Patent No.",
  },
  ar: {
    getStarted: "ابدأ مجانًا",
    getStartedShort: "ابدأ",
    learnMore: "اعرف المزيد",
    seeAllModules: "استعرض الوحدات الـ14",
    downloadApp: "حمّله من Google Play",
    openWebApp: "افتح نسخة الويب",
    contactUs: "تواصل معنا",
    menu: "قائمة التنقل",
    close: "إغلاق القائمة",
    language: "اللغة",
    backToModules: "كل الوحدات",
    worksWellWith: "تعمل جيدًا مع",
    whatItIs: "ما هي",
    howItWorks: "كيف تعمل",
    everythingItDoes: "كل ما تقدّمه",
    whoItsFor: "لمن هي",
    whatItCosts: "التكلفة",
    whereItSettles: "أين تستقرّ الأموال",
    seeItWork: "شاهدها تعمل",
    moneyStack: "المنظومة المالية",
    businessStack: "المنظومة التجارية",
    status: { live: "متاح", beta: "تجريبي", planned: "قريبًا" },
    filterAll: "الكل",
    browse: "تصفّح",
    company: "الشركة",
    support: "الدعم",
    legal: "قانوني",
    followUs: "تابعنا",
    rightsReserved: "جميع الحقوق محفوظة.",
    poweredBy: "مُشغَّل بواسطة",
    patentNo: "رقم البراءة",
  },
  fr: {
    getStarted: "Commencer gratuitement",
    getStartedShort: "Commencer",
    learnMore: "En savoir plus",
    seeAllModules: "Voir les 14 modules",
    downloadApp: "Disponible sur Google Play",
    openWebApp: "Ouvrir la version web",
    contactUs: "Nous contacter",
    menu: "Navigation",
    close: "Fermer le menu",
    language: "Langue",
    backToModules: "Tous les modules",
    worksWellWith: "Fonctionne bien avec",
    whatItIs: "Qu'est-ce que c'est",
    howItWorks: "Comment ça marche",
    everythingItDoes: "Tout ce qu'il fait",
    whoItsFor: "À qui ça s'adresse",
    whatItCosts: "Combien ça coûte",
    whereItSettles: "Où l'argent arrive",
    seeItWork: "Voir en action",
    moneyStack: "Pôle financier",
    businessStack: "Pôle commercial",
    status: { live: "Disponible", beta: "Bêta", planned: "Bientôt" },
    filterAll: "Tous",
    browse: "Parcourir",
    company: "Entreprise",
    support: "Assistance",
    legal: "Mentions légales",
    followUs: "Suivez-nous",
    rightsReserved: "Tous droits réservés.",
    poweredBy: "Propulsé par",
    patentNo: "Brevet n°",
  },
  pt: {
    getStarted: "Começar gratuitamente",
    getStartedShort: "Começar",
    learnMore: "Saber mais",
    seeAllModules: "Ver os 14 módulos",
    downloadApp: "Disponível no Google Play",
    openWebApp: "Abrir a versão web",
    contactUs: "Fale connosco",
    menu: "Navegação",
    close: "Fechar o menu",
    language: "Idioma",
    backToModules: "Todos os módulos",
    worksWellWith: "Funciona bem com",
    whatItIs: "O que é",
    howItWorks: "Como funciona",
    everythingItDoes: "Tudo o que faz",
    whoItsFor: "Para quem é",
    whatItCosts: "Quanto custa",
    whereItSettles: "Onde o dinheiro entra",
    seeItWork: "Ver a funcionar",
    moneyStack: "Bloco financeiro",
    businessStack: "Bloco comercial",
    status: { live: "Disponível", beta: "Beta", planned: "Em breve" },
    filterAll: "Todos",
    browse: "Explorar",
    company: "Empresa",
    support: "Apoio",
    legal: "Informação legal",
    followUs: "Siga-nos",
    rightsReserved: "Todos os direitos reservados.",
    poweredBy: "Desenvolvido por",
    patentNo: "Patente n.º",
  },
});

export const COMPANY_ADDRESS = pick(COMPANY.address);

/** Slogan under the floating logo watermark. */
export const SLOGAN = pick({
  en: "Same vision, evolved experience",
  ar: "نفس الرؤية، تجربة متطورة",
  fr: "Même vision, expérience réinventée",
  pt: "A mesma visão, uma experiência renovada",
});
